from pathlib import Path
from zipfile import ZipFile, ZIP_DEFLATED
import shutil

from pptx import Presentation

from generate_pfe_presentation_luxury_openxml import (
    Deck,
    C,
    SHOT_DIR,
    LOGO,
    add_picture,
    add_screenshot,
)

OUT = Path(__file__).resolve().parent / "presentation-pfe-focal-assist-v3-premium.pptx"


def patch_office_theme(pptx_path: Path):
    """Replace the minimal generated theme with an Office-compatible theme.

    PowerPoint is stricter than XML parsers: an empty theme formatting scheme can
    trigger "file needs repair" even when the package is well-formed. The slide
    content remains generated by the custom OpenXML deck, but the theme part is
    sourced from a standards-compliant blank presentation.
    """
    blank = pptx_path.with_name("_office_theme_source.pptx")
    temp = pptx_path.with_suffix(".tmp.pptx")
    Presentation().save(str(blank))
    with ZipFile(blank) as source_zip:
        theme_xml = source_zip.read("ppt/theme/theme1.xml")
    with ZipFile(pptx_path) as zin, ZipFile(temp, "w", ZIP_DEFLATED) as zout:
        for item in zin.infolist():
            data = zin.read(item.filename)
            if item.filename == "ppt/theme/theme1.xml":
                data = theme_xml
            zout.writestr(item, data)
    temp.replace(pptx_path)
    blank.unlink(missing_ok=True)


def section(slide, label: str, title: str, subtitle: str = ""):
    slide.text(label.upper(), 54, 62, 240, 16, 8, C["cyan"], True)
    slide.text(title, 54, 84, 845, 44, 26, C["navy"], True)
    slide.line_rect(54, 133, 92, 4, C["cyan"])
    slide.line_rect(153, 133, 42, 4, C["blue"])
    if subtitle:
        slide.text(subtitle, 54, 148, 820, 28, 11, C["muted"])


def mini_card(slide, title, text, x, y, w=250, h=118, accent=C["blue"]):
    slide.rect(x, y, w, h, C["white"], C["border"])
    slide.line_rect(x, y, w, 5, accent)
    slide.text(title, x + 18, y + 18, w - 36, 20, 15, accent, True)
    slide.text(text, x + 18, y + 48, w - 36, h - 58, 9, C["ink"])


def bullet_panel(slide, title, items, x=70, y=165, w=820, h=270, accent=C["blue"]):
    # Conservative dimensions: PowerPoint can wrap differently from the generator,
    # so short panels are expanded and bullet typography stays compact.
    h = max(h, 155 if len(items) >= 3 else 130)
    bullet_size = 11 if h < 190 or w < 760 else 12
    slide.rect(x, y, w, h, C["white"], C["border"])
    slide.line_rect(x, y, w, 5, accent)
    slide.text(title, x + 24, y + 20, w - 48, 22, 16, accent, True)
    slide.bullets(items, x + 28, y + 58, w - 56, h - 72, bullet_size)


def screenshot_slide(deck, title, file_name, notes, module_label="DEMONSTRATION V3"):
    s = deck.add_slide(module_label)
    section(s, module_label, title, "Capture reelle de l'application. L'objectif est de montrer le module et son role dans le workflow global.")
    add_screenshot(s, deck, SHOT_DIR / file_name, 46, 155, 650, 335, "rIdShot")
    s.rect(724, 155, 184, 335, C["white"], C["border"])
    s.line_rect(724, 155, 184, 5, C["cyan"])
    s.text("A presenter", 744, 178, 140, 22, 15, C["blue"], True)
    s.bullets(notes[:4], 744, 218, 140, 190, 10)
    s.text("Message cle", 744, 438, 140, 16, 9, C["muted"], True)
    s.text(notes[-1] if notes else "Module integre dans V3.", 744, 458, 140, 26, 9, C["ink"])


def class_cards(slide, boxes):
    for name, attrs, x, y, w, h, color in boxes:
        slide.class_box(name, attrs, x, y, w, h, color)


def lower_class_cards(slide, boxes):
    safe_boxes = []
    for name, attrs, x, y, w, h, color in boxes:
        yy = y + 38 if y < 250 else y + 24
        safe_boxes.append((name, attrs, x, yy, w, h, color))
    class_cards(slide, safe_boxes)


def flow_slide(deck, title, subtitle, steps, notes, label="SEQUENCE"):
    s = deck.add_slide(label)
    section(s, label, title, subtitle)
    s.flow(steps, 48, 180, 865)
    bullet_panel(s, "Lecture technique", notes, 78, 318, 805, 145, C["cyan"])


def build():
    d = Deck()

    # 1 Cover
    s = d.add_slide("PFE")
    s.rect(40, 42, 458, 405, C["white"], C["border"])
    if LOGO.exists():
        add_picture(s, d, LOGO, 58, 50, 180, 70, "rIdLogo")
    s.text("PROJET DE FIN D'ETUDES", 58, 132, 260, 18, 10, C["cyan"], True)
    s.text("Focal V3", 58, 165, 400, 46, 34, C["navy"], True)
    s.text(
        "Plateforme full stack d'assistance operationnelle, knowledge management, IA et pilotage support.",
        58,
        220,
        390,
        78,
        16,
        C["ink"],
        True,
    )
    s.text("Cycle d'ingenieur | ISMAGI | 2025 - 2026", 58, 310, 360, 22, 13, C["muted"])
    s.text("Abdelfattah AZELMADI", 58, 342, 360, 24, 16, C["navy"], True)
    s.rect(58, 382, 178, 28, C["navy"], C["cyan"])
    s.text("Soutenance PFE", 80, 390, 130, 10, 9, C["white"], True)
    add_screenshot(s, d, SHOT_DIR / "02-command-center.png", 530, 78, 350, 230, "rIdHero")
    mini_card(
        s,
        "Positionnement",
        "Un cockpit unique pour agents, superviseurs, QA, admins et operations.",
        530,
        330,
        350,
        105,
        C["cyan"],
    )

    # 2 Executive summary
    s = d.add_slide("Synthese")
    section(s, "SYNTHÈSE", "Résumé exécutif", "Le projet répond à un besoin réel : rendre les opérations support plus rapides, cohérentes et mesurables.")
    mini_card(s, "Probleme", "Outils disperses, procedures non centralisees, faible tracabilite.", 60, 180, 255, 125, C["red"])
    mini_card(s, "Solution", "V3 Shell : CRM, KB, IA, chat, QA, formation, roles et escalation.", 352, 180, 255, 125, C["blue"])
    mini_card(s, "Valeur", "Productivite agent, qualite de reponse, pilotage et scalabilite.", 644, 180, 255, 125, C["green"])
    bullet_panel(
        s,
        "Angle de soutenance",
        [
            "Presenter Focal V3 comme une plateforme produit, pas comme une simple application.",
            "Montrer la maitrise full stack : Angular, Spring Boot, MySQL, securite, WebSocket, Docker.",
            "Mettre en avant la valeur metier : support fintech, knowledge, quality, automation.",
        ],
        96,
        345,
        770,
        115,
        C["cyan"],
    )

    # 3 Sommaire
    s = d.add_slide("Plan")
    section(s, "PLAN", "Sommaire de soutenance", "Structure académique complète, enrichie par des diagrammes techniques et des captures réelles.")
    s.flow(["Contexte", "Besoin", "Solution", "Conception", "Realisation", "Demo", "Bilan"], 45, 178, 870)
    bullet_panel(
        s,
        "Fil conducteur",
        [
            "Partir du probleme operationnel d'une fintech.",
            "Demontrer l'architecture et les choix de conception.",
            "Prouver le resultat avec des captures reelles de chaque page V3.",
            "Conclure sur les limites, perspectives et valeur professionnelle.",
        ],
        90,
        322,
        780,
        132,
        C["blue"],
    )

    # Core academic slides
    core = [
        (
            "Contexte du projet",
            "Les fintechs doivent traiter vite, juste et de manière traçable.",
            [
                "Le support client est critique dans une fintech : il influence confiance, retention et conformite.",
                "Les agents manipulent des cas sensibles : KYC, paiement, remboursement, blocage compte, reclamation.",
                "La connaissance doit etre centralisee, mesurable et directement exploitable pendant le traitement.",
            ],
            "CONTEXTE",
        ),
        (
            "Problématique",
            "Comment industrialiser le support client sans sacrifier la qualité ?",
            [
                "Centraliser les interactions, procedures, formations et escalades dans un meme cockpit.",
                "Garantir la coherence des reponses entre agents et equipes.",
                "Rendre les operations mesurables : temps article, statuts, QA, tickets, usage IA.",
                "Securiser les donnees et limiter les modules selon le role.",
            ],
            "PROBLÉMATIQUE",
        ),
        (
            "Objectifs",
            "Construire un outil opérationnel, pas seulement une interface.",
            [
                "Ameliorer la productivite agents avec CRM, KB, SOP maps et Magic Assistance.",
                "Donner aux managers des dashboards exploitables : KB Analytics, adherence, QA.",
                "Ajouter une IA controlee via prompts par role et conversations historisees.",
                "Preparer le produit a un deploiement Docker, cloud ou self-hosted.",
            ],
            "OBJECTIFS",
        ),
        (
            "Analyse des besoins",
            "Les besoins sont structurés par acteur et par responsabilité.",
            [
                "Agent : traiter, chercher, suivre une procedure, escalader et apprendre.",
                "Team Leader : suivre son equipe, analyser les statuts et les performances.",
                "QA : evaluer les cas, historiser les scores et donner du feedback.",
                "Admin/OPS : gerer comptes, droits, workflows, articles, prompts et integrations.",
            ],
            "ANALYSE",
        ),
        (
            "Cahier des charges",
            "Les exigences couvrent la fonction, la sécurité et l'exploitation.",
            [
                "Fonctionnel : CRM, KB, chat, IA, training, QA, roles, escalation, builders.",
                "Technique : API REST, WebSocket, base relationnelle, Docker, integration Gmail/Jira/OpenAI.",
                "Securite : JWT, comptes actifs/desactives, RoleGuard et controle backend.",
                "UX : shell stable, navigation lisible, maps visuelles, feedback immediat.",
            ],
            "CAHIER DES CHARGES",
        ),
        (
            "Étude de l'existant",
            "Le marché est mature, mais fragmenté selon les usages.",
            [
                "Zendesk est fort en support, mais couteux et parfois lourd pour les workflows internes.",
                "Helpjuice est fort en Knowledge Base, mais moins centre sur CRM, QA et operations.",
                "Slack est excellent en collaboration, mais pas relie nativement aux SOP et analytics KB.",
                "Jira est puissant pour L2/tech, mais pas adapte seul au travail quotidien L1.",
            ],
            "EXISTANT",
        ),
        (
            "Solution proposée",
            "Focal V3 regroupe support, connaissance, IA et pilotage.",
            [
                "Un shell V3 unique avec sidebar, topbar et routes role-based.",
                "Des modules independants mais coherents : CRM, KB, Magic Assistance, Academy, QA, Chat.",
                "Des builders visuels pour adapter les processus sans modification du code.",
                "Une architecture extensible vers SaaS, self-hosted, SSO et canaux omnicanaux.",
            ],
            "SOLUTION",
        ),
    ]
    for title, subtitle, bullets, label in core:
        s = d.add_slide(label)
        section(s, label, title, subtitle)
        bullet_panel(s, "Points essentiels", bullets, 78, 170, 805, 230, C["blue"])

    # Technologies
    s = d.add_slide("TECHNOLOGIES")
    section(s, "TECHNOLOGIES", "Stack technique utilisée", "Une architecture moderne, lisible et cohérente avec un projet full stack professionnel.")
    s.flow(["Angular 21", "Spring Boot 4", "REST", "WebSocket", "MySQL", "Docker"], 42, 178, 875)
    bullet_panel(
        s,
        "Choix techniques",
        [
            "Angular : composants standalone, routes lazy-loaded, services HTTP, UI modulaire.",
            "Spring Boot : controllers, services, repositories JPA, security filters.",
            "MySQL/MariaDB : persistence metier, historiques, logs, relations et analytics.",
            "Docker : packaging, isolation et preparation au deploiement cloud/VPS.",
        ],
        78,
        322,
        805,
        132,
        C["cyan"],
    )

    # UX conception
    s = d.add_slide("CONCEPTION")
    section(s, "CONCEPTION", "Conception UX/UI", "Une interface structurée pour réduire la charge cognitive et accélérer les actions quotidiennes.")
    mini_card(s, "Shell stable", "Sidebar + topbar constantes pour garder les reperes.", 62, 180, 250, 115, C["blue"])
    mini_card(s, "Maps visuelles", "Canvas, nodes, links, zoom, pan et inspecteurs.", 355, 180, 250, 115, C["cyan"])
    mini_card(s, "Feedback", "Toasts, loaders, status, messages, erreurs et confirmations.", 648, 180, 250, 115, C["green"])
    add_screenshot(s, d, SHOT_DIR / "27-role-access-map.png", 120, 328, 720, 150, "rIdUx")

    # Use cases
    s = d.add_slide("DIAGRAMMES")
    section(s, "DIAGRAMME DE CAS D'UTILISATION", "Vue globale des acteurs", "Chaque acteur a un périmètre fonctionnel précis, contrôlé par rôle et feature access.")
    s.flow(["Client public", "Agent", "Team Leader", "QA", "Admin", "OPS"], 42, 178, 875)
    bullet_panel(
        s,
        "Cas d'utilisation majeurs",
        [
            "Client public : demarrer une conversation, suivre le bot, escalader, donner un CSAT.",
            "Agent : traiter CRM, consulter KB, suivre Magic Assistance, collaborer, se former.",
            "Supervision : analyser adherence, QA, KB usage, tickets et activite equipe.",
            "Administration : gerer comptes, roles, maps, articles, prompts, chat projects.",
        ],
        78,
        322,
        805,
        132,
        C["cyan"],
    )

    s = d.add_slide("DIAGRAMMES")
    section(s, "CAS D'UTILISATION", "Détail par responsabilité", "Lecture plus précise des responsabilités métier dans l'application.")
    mini_card(s, "Agent", "CRM, KB, SOP, Magic Assistance, formation, chat assigne.", 62, 180, 250, 130, C["blue"])
    mini_card(s, "Supervision", "Adherence, QA, analytics, tickets equipe, suivi performance.", 355, 180, 250, 130, C["cyan"])
    mini_card(s, "Admin/OPS", "Comptes, roles, builders, prompts, articles, integrations.", 648, 180, 250, 130, C["green"])
    bullet_panel(s, "Principe", ["Chaque action visible doit correspondre a un droit.", "Les modules non relies au role ne doivent pas apparaitre.", "La securite doit etre appliquee cote backend, pas uniquement cote UI."], 120, 350, 720, 115, C["blue"])

    # Class diagrams overview and domain slides
    s = d.add_slide("DIAGRAMMES")
    section(s, "DIAGRAMME DE CLASSES", "Vue d'ensemble du modèle", "Le modèle est découpé par bounded contexts pour garder un diagramme lisible.")
    s.flow(["Identity", "Knowledge", "CRM", "Collab", "Chat", "AI", "Training", "Ops"], 35, 178, 890)
    bullet_panel(
        s,
        "Lecture du modèle",
        [
            "User est l'entite transversale pour roles, settings, presence, QA et assignations.",
            "KbArticle relie contenu, categories, maps, feedbacks et tracking temps.",
            "ChatProject isole workflows, queues, agents, API keys et sessions publiques.",
            "EscalationTicket separe le support L1/L2 du CRM email et du suivi Jira.",
        ],
        78,
        322,
        805,
        132,
        C["cyan"],
    )

    class_slides = [
        (
            "Identity & Access",
            [
                ("User", ["id", "email", "role", "active", "status"], 58, 170, 190, 110, C["blue"]),
                ("UserStatus", ["userId", "status", "updatedAt"], 285, 170, 180, 100, C["cyan"]),
                ("UserStatusHistory", ["fromStatus", "toStatus", "createdAt"], 505, 170, 195, 100, C["cyan"]),
                ("RoleAccessProfile", ["roleKey", "label", "active"], 740, 170, 170, 100, C["green"]),
                ("RoleAccessLink", ["roleKey", "featureKey", "enabled"], 170, 330, 190, 100, C["green"]),
                ("TeamLink", ["agentId", "tlId", "qaId"], 405, 330, 180, 100, C["orange"]),
                ("UserSettings", ["language", "timezone", "jira", "notifications"], 630, 330, 195, 100, C["blue"]),
            ],
        ),
        (
            "Knowledge & Decision",
            [
                ("KbCategory", ["id", "name", "order"], 45, 165, 170, 96, C["blue"]),
                ("KbArticle", ["title", "contentHtml", "active"], 255, 165, 185, 105, C["blue"]),
                ("KbMapNode", ["articleId", "title", "x", "y"], 480, 165, 190, 105, C["cyan"]),
                ("KbMapEdge", ["source", "target", "label"], 710, 165, 185, 96, C["cyan"]),
                ("KbTimeLog", ["articleId", "userId", "seconds"], 45, 330, 185, 96, C["green"]),
                ("Page", ["title", "content", "tag"], 280, 330, 170, 90, C["orange"]),
                ("Choice", ["label", "sourcePage", "targetPage"], 500, 330, 190, 96, C["orange"]),
                ("CaseTagNode/Edge", ["label", "parent", "target"], 730, 330, 170, 90, C["green"]),
            ],
        ),
        (
            "CRM & Communication",
            [
                ("CemContact", ["name", "email", "phone"], 55, 165, 170, 96, C["blue"]),
                ("CemConversation", ["subject", "status", "assignee"], 270, 165, 200, 105, C["blue"]),
                ("CemInternalNote", ["authorId", "content", "createdAt"], 515, 165, 200, 105, C["cyan"]),
                ("GmailAccount", ["email", "tokens", "expiresAt"], 745, 165, 170, 105, C["green"]),
                ("ChatChannelLink", ["provider", "externalId", "active"], 55, 330, 180, 96, C["orange"]),
                ("ChatConversation", ["channel", "customer", "status"], 285, 330, 180, 96, C["orange"]),
                ("ChatMessage", ["sender", "body", "sentAt"], 515, 330, 190, 100, C["orange"]),
                ("ChatParticipant", ["userId", "role", "joinedAt"], 745, 330, 170, 96, C["orange"]),
            ],
        ),
        (
            "Live Chat Routing",
            [
                ("ChatProject", ["name", "slug", "status", "api"], 55, 165, 180, 100, C["cyan"]),
                ("ChatApiKey", ["projectId", "tokenHash", "scope"], 280, 165, 190, 100, C["cyan"]),
                ("ChatWorkflow", ["projectId", "status", "publishedAt"], 515, 165, 190, 96, C["cyan"]),
                ("WorkflowNode", ["type", "payload", "x", "y"], 745, 165, 170, 100, C["cyan"]),
                ("ChatQueue", ["projectId", "name", "status"], 55, 330, 180, 96, C["green"]),
                ("QueueAgent", ["queueId", "userId", "priority"], 280, 330, 190, 96, C["green"]),
                ("LiveSession", ["projectId", "queueId", "status"], 515, 330, 190, 100, C["blue"]),
                ("LiveMessage", ["sessionId", "sender", "body"], 745, 330, 170, 100, C["blue"]),
            ],
        ),
        (
            "AI, Training, QA & Ops",
            [
                ("AIConversation", ["userId", "title", "profileId"], 45, 165, 190, 96, C["blue"]),
                ("AIMessage", ["role", "content", "createdAt"], 275, 165, 190, 96, C["blue"]),
                ("PromptProfile", ["prompt", "model", "apiKey"], 505, 165, 190, 96, C["cyan"]),
                ("TrainingAsset", ["type", "path", "duration"], 735, 165, 175, 96, C["green"]),
                ("QaEvaluation", ["ticketId", "agentId", "score"], 160, 330, 190, 96, C["green"]),
                ("EscalationTicket", ["clientId", "priority", "status", "jiraKey"], 395, 330, 205, 100, C["orange"]),
                ("EscalationComment", ["ticketId", "authorId", "body"], 650, 330, 180, 96, C["orange"]),
            ],
        ),
    ]
    for title, boxes in class_slides:
        s = d.add_slide("CLASSES")
        section(s, "DIAGRAMME DE CLASSES", title, "Les classes sont présentées par domaine pour éviter un schéma illisible.")
        lower_class_cards(s, boxes)

    # Class inventory split
    inventories = [
        ("Inventaire des classes - Socle", ["User, UserStatus, UserStatusHistory, TeamLink", "RoleAccessProfile, RoleAccessLink, UserSettings", "KbCategory, KbArticle, KbMapNode, KbMapEdge", "KbArticleTimeLog, Page, Choice, CaseTagNode, CaseTagEdge"]),
        ("Inventaire des classes - Communication", ["CemContact, CemConversation, CemInternalNote, GmailAccount", "CollaborationRoom, CollaborationRoomMember, CollaborationMessage", "CollaborationMessageMention, Reaction, ArticleLink", "ChatChannelLink, ChatConversation, ChatMessage, ChatParticipant"]),
        ("Inventaire des classes - Automation & Ops", ["ChatProject, ChatProjectApiKey, ChatWorkflow, ChatWorkflowNode, ChatWorkflowConnection", "ChatQueue, ChatQueueAgent, LiveChatSession, LiveChatMessage, LiveChatAssignment", "ProcessAssistantConversation, ProcessAssistantMessage, PromptProfile, PromptRoleLink", "TrainingAsset, QaEvaluation, EscalationTicket, EscalationComment, WorkflowExecution"]),
    ]
    for title, items in inventories:
        s = d.add_slide("CLASSES")
        section(s, "INVENTAIRE", title, "Résumé des principales entités persistées dans la base de données.")
        bullet_panel(s, "Classes principales", items, 78, 175, 805, 215, C["cyan"])

    # Sequence diagrams
    flows = [
        ("Login et accès V3", ["Utilisateur", "Login", "Auth API", "JWT", "V3 Shell", "RoleGuard"], ["Saisie credentials", "Validation Spring Security", "Emission JWT", "Chargement profil et droits", "Blocage des pages non autorisees"]),
        ("Lecture article et analytics", ["Agent", "KB", "Article API", "Timer", "Analytics", "Dashboard"], ["Selection article", "Chargement contenu et SOP map", "Heartbeat temps de lecture", "Feedback like/dislike", "Consolidation par agent et article"]),
        ("Public Chat vers agent", ["Client", "Public Chat", "Workflow", "Queue", "Assign", "Agent"], ["Session publique sans login", "Execution du decision tree", "Escalade vers queue", "Assignation agent disponible", "Conversation WebSocket + CSAT"]),
        ("Escalade L1/L2 et Jira", ["L1", "Ticket API", "Queue L2", "Playlist", "Jira", "Status"], ["Creation ticket avec Client ID", "Detection doublons", "Play verrouille le plus ancien ticket", "Creation/suivi Jira via backend", "Resolution controlee"]),
    ]
    for title, steps, notes in flows:
        flow_slide(d, title, "Séquence technique de bout en bout, simplifiée pour soutenance.", steps, notes)

    # Architecture
    arch = [
        ("Modèle de données", ["User centralise roles, settings, presence et assignations.", "KbArticle relie categorie, contenu, SOP map, feedback et tracking.", "ChatProject isole workflow, queues, API keys et sessions.", "EscalationTicket relie support L1/L2 et Jira sans melanger le CRM."]),
        ("Architecture du système", ["Angular V3 gere UI, routes, guards et services HTTP.", "Spring Boot applique securite, logique metier, REST et WebSocket.", "MySQL/MariaDB persiste les donnees relationnelles et historiques.", "Les integrations externes passent par backend pour proteger les secrets."]),
        ("Architecture de déploiement", ["HTTPS et reverse proxy pour TLS, /api et /ws.", "Frontend Angular SSR ou build web selon cible.", "Backend Spring Boot en service separe.", "MySQL avec volume, backups et restrictions reseau."]),
        ("Carte des APIs backend", ["/auth/login : authentification.", "/api/kb, /api/kb-map, /api/kb/analytics : connaissance.", "/api/crm, /api/gmail, /api/case-tags : CRM.", "/api/chat-projects, /api/public/chat, /api/live-chat : chat.", "/api/process-assistant, /api/access-control, /api/escalations : IA, roles, L1/L2."]),
        ("Développement / Implémentation", ["Frontend : composants Angular standalone et routes lazy-loaded.", "Backend : controllers REST, services metier, repositories JPA.", "Temps reel : WebSocket pour collaboration et live chat.", "Documentation : rapport, guides de deploiement, scripts de generation."]),
    ]
    for title, items in arch:
        s = d.add_slide("ARCHITECTURE")
        section(s, "ARCHITECTURE", title, "Vue technique structurée et adaptée à une présentation d’ingénierie.")
        if "système" in title.lower():
            s.flow(["Angular V3", "REST API", "Spring Services", "JPA", "MySQL"], 58, 185, 845)
            bullet_panel(s, "Responsabilites", items, 100, 325, 760, 128, C["cyan"])
        elif "déploiement" in title.lower() or "deploiement" in title.lower():
            s.flow(["HTTPS", "Reverse Proxy", "Angular", "Spring API", "MySQL", "Volumes"], 40, 185, 880)
            bullet_panel(s, "Cible cloud/VPS", items, 100, 325, 760, 128, C["blue"])
        else:
            bullet_panel(s, "Details", items, 78, 175, 805, 245, C["cyan"])

    # Function overview
    s = d.add_slide("FONCTIONNALITES")
    section(s, "FONCTIONNALITES", "Fonctionnalités principales", "Vue claire des modules qui seront démontrés dans la suite.")
    mini_card(s, "CRM", "Emails, tickets, notes internes, tags, pieces jointes.", 58, 175, 250, 105, C["blue"])
    mini_card(s, "Knowledge", "Articles, SOP maps, feedback, analytics d'usage.", 355, 175, 250, 105, C["cyan"])
    mini_card(s, "AI", "Process Copilot, prompts par role, historique.", 652, 175, 250, 105, C["green"])
    mini_card(s, "Operations", "QA, adherence, training, escalade L1/L2, Jira.", 208, 330, 250, 105, C["orange"])
    mini_card(s, "Chat", "Collaboration, live chat, chat projects, workflow bot.", 505, 330, 250, 105, C["blue"])

    # Demo screenshot slides, one per page.
    screens = [
        ("Login", "01-login.png", ["Authentification securisee", "Message d'erreur clair", "Animation login", "Entrée vers V3"]),
        ("Command Center", "02-command-center.png", ["Cockpit central", "Quick jumps", "Navigation par role", "Point d'entree produit"]),
        ("Calendar", "03-calendar.png", ["Planification", "Evenements", "Organisation equipe", "Vision temporelle"]),
        ("CRM Inbox", "04-crm-inbox.png", ["Emails et tickets", "Files de traitement", "Statuts", "Travail agent"]),
        ("CRM Ticket Detail", "05-crm-ticket-detail.png", ["Conversation client", "Composer", "Notes internes", "Traçabilité"]),
        ("Magic Assistance", "06-magic-assistance.png", ["Decision tree", "Guidage agent", "Processus", "Cohérence réponse"]),
        ("Knowledge Base", "07-knowledge-base.png", ["Articles", "Recherche", "SOP map", "Feedback agent"]),
        ("KB Analytics", "08-kb-analytics.png", ["Temps de lecture", "Articles consultes", "Agents", "Pilotage knowledge"]),
        ("Collaboration Hub", "09-collaboration-hub.png", ["Canaux", "DM", "Messages", "Coordination interne"]),
        ("Chat Projects", "10-chat-projects.png", ["Chatbots publics", "Workflow", "Queues", "API project"]),
        ("Live Chat", "11-live-chat.png", ["Sessions clients", "Assignation", "Conversation", "Temps reel"]),
        ("Process Copilot", "12-process-assistant.png", ["Assistant IA", "Prompts par role", "Historique", "Support agent"]),
        ("Academy - My Trainings", "13-academy-home.png", ["Formations", "Progression", "Parcours", "Montée compétence"]),
        ("Academy - Catalog", "14-academy-catalog.png", ["Catalogue", "Recherche", "Cours", "Autoformation"]),
        ("Academy - Course Viewer", "15-academy-course-viewer.png", ["Lecture cours", "Étapes", "Vidéo", "Suivi temps"]),
        ("Academy - Certificate", "16-academy-certificate.png", ["Certificat", "Validation", "Reconnaissance", "Fin parcours"]),
        ("Academy - Studio", "17-academy-studio.png", ["Création cours", "Modules", "Contenu", "Publication"]),
        ("Academy - Course Editor", "18-academy-course-editor.png", ["Edition", "Sections", "Médias", "Quiz"]),
        ("Academy - Analytics", "19-academy-analytics.png", ["Suivi formation", "Temps", "Completion", "Management"]),
        ("Staff Management", "20-staff-management.png", ["Comptes", "Activation", "Rôles", "Administration"]),
        ("Tree Builder", "21-tree-builder.png", ["Noeuds", "Connecteurs", "Auto-layout", "Save DB"]),
        ("KB Map Builder", "22-kb-map-builder.png", ["SOP article", "Canvas", "Détails", "Pan/zoom"]),
        ("Case Tag Builder", "23-case-tag-builder.png", ["Typologies", "Catégories", "Sous-catégories", "Classification"]),
        ("Prompt Map Builder", "24-prompt-map-builder.png", ["Prompts", "Rôles", "Clés API", "LLM governance"]),
        ("Article Management", "25-article-management.png", ["CRUD articles", "Catégories", "Edition", "Publication"]),
        ("Article Editor", "26-article-editor.png", ["Edition full page", "Contenu riche", "Sauvegarde", "Gestion KB"]),
        ("Role Access Map", "27-role-access-map.png", ["Rôles", "Features", "Liens", "Permissions"]),
        ("Settings", "28-settings.png", ["Profil", "Mot de passe", "Jira", "Préférences"]),
        ("Adherence Dashboard", "29-adherence-dashboard.png", ["Timeline", "Statuts", "Agents", "Supervision"]),
        ("QA Evaluation", "30-qa-evaluation.png", ["Scores", "Evaluation", "Feedback", "Qualité"]),
        ("Team Management", "31-team-management.png", ["TL/QA", "Agents", "Mapping", "Organisation"]),
        ("Channel Access Map", "32-channel-access-map.png", ["Canaux", "Invitations", "Accès", "Collaboration"]),
        ("FlowDesk Board", "33-flowdesk-board.png", ["Board", "Delivery", "Tickets", "Suivi"]),
        ("FlowDesk Backlog", "34-flowdesk-backlog.png", ["Backlog", "Priorités", "Demandes", "Préparation"]),
        ("FlowDesk Sprints", "35-flowdesk-sprints.png", ["Sprints", "Planification", "Execution", "Suivi"]),
        ("FlowDesk Reports", "36-flowdesk-reports.png", ["Rapports", "KPI", "Analyse", "Delivery"]),
        ("FlowDesk Escalations", "37-flowdesk-escalations.png", ["L1/L2", "Playlist", "Jira", "Résolution"]),
        ("404 Page", "38-v3-not-found.png", ["Page erreur", "Robustesse UX", "Retour", "Navigation"]),
        ("Article Not Found", "39-article-not-found.png", ["Article manquant", "UX erreur", "Retour KB", "Contrôle"]),
    ]
    for title, img, notes in screens:
        screenshot_slide(d, title, img, notes)

    endings = [
        ("Difficultés rencontrées et solutions", ["Change detection Angular : refresh d'etat, listeners et guards.", "Integrations : Gmail token, Jira CORS, OpenAI quota et API keys.", "Builders visuels : connecteurs, pan/zoom, alignement et lisibilite.", "Production : secrets, Docker, reverse proxy, base persistante et sauvegardes."]),
        ("Résultats obtenus", ["Une plateforme V3 demonstrable avec plus de 20 modules.", "39 captures reelles integrees pour appuyer la soutenance.", "Architecture full stack modulaire et extensible.", "Base solide pour prototype SaaS, self-hosted ou PFE avance."]),
        ("Limites du projet", ["Remplacer ddl-auto update par migrations versionnees.", "Renforcer tests unitaires, integration, E2E et charge.", "Ajouter observabilite : logs structures, metrics, alertes.", "Durcir secrets, permissions serveur et procedure production."]),
        ("Perspectives d'amélioration", ["SSO Keycloak et multi-tenancy.", "RAG et recherche semantique sur la Knowledge Base.", "Canaux officiels : WhatsApp, Instagram, Messenger, Telegram.", "Kubernetes, CI/CD, monitoring, SLA et business hours."]),
        ("Conclusion", ["Focal V3 depasse une application CRUD classique.", "Le projet combine produit, architecture, UX, securite, IA et operations.", "La valeur : agents plus rapides, reponses plus coherentes, pilotage plus mesurable."]),
    ]
    for title, items in endings:
        s = d.add_slide("BILAN")
        section(s, "BILAN", title, "Synthèse professionnelle pour conclure la soutenance.")
        bullet_panel(s, "À retenir", items, 78, 175, 805, 225, C["cyan"])

    s = d.add_slide("QUESTIONS")
    s.rect(0, 0, 960, 540, C["navy"], None, "rect")
    s.line_rect(0, 0, 960, 6, C["cyan"])
    s.text("Questions ?", 80, 155, 700, 68, 48, C["white"], True)
    s.text("Merci pour votre attention", 84, 235, 600, 30, 20, C["cyan"], True)
    s.text("Projet de Fin d'Etudes - Focal V3 - Abdelfattah AZELMADI", 84, 420, 760, 24, 13, "D2DCEB")

    return d


if __name__ == "__main__":
    deck = build()
    deck.save(OUT)
    patch_office_theme(OUT)
    print(OUT)
    print(f"slides={len(deck.slides)}")
    print(f"media={len(deck.media)}")
